//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVIDADES_DEMANADAS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ACTIVIDADES_DEMANADAS()
    {
        this.HORARIS_ACT_DEMANADA = new HashSet<HORARIS_ACT_DEMANADA>();
    }

    public int id { get; set; }
    public string nom { get; set; }
    public string durada { get; set; }
    public int id_equipo { get; set; }
    public int id_espai { get; set; }
    public int id_tipus_actividad { get; set; }
    public bool revisada { get; set; }

    public virtual EQUIPS EQUIPS { get; set; }
    public virtual LLOC_DEPORTIVO LLOC_DEPORTIVO { get; set; }
    public virtual TIPUS_ACTIVIDAD TIPUS_ACTIVIDAD { get; set; }
    public virtual ACTIVITATS ACTIVITATS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HORARIS_ACT_DEMANADA> HORARIS_ACT_DEMANADA { get; set; }
}
