//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspaiActiu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIES_SETMANA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIES_SETMANA()
        {
            this.HORARIS_ACT_DEMANADA = new HashSet<HORARIS_ACT_DEMANADA>();
            this.HORARIS_INSTALACIO = new HashSet<HORARIS_INSTALACIO>();
            this.HORARIS_ACTIVITAT = new HashSet<HORARIS_ACTIVITAT>();
        }
    
        public byte id { get; set; }
        public string dia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_ACT_DEMANADA> HORARIS_ACT_DEMANADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_INSTALACIO> HORARIS_INSTALACIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_ACTIVITAT> HORARIS_ACTIVITAT { get; set; }
    }
}
