//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class INCIDENCIA
{
    public int id { get; set; }
    public int id_entidad { get; set; }
    public int id_lloc { get; set; }
    public string descripcion { get; set; }
    public int id_tipo_incidencia { get; set; }

    public virtual ENTITATS ENTITATS { get; set; }
    public virtual LLOC_DEPORTIVO LLOC_DEPORTIVO { get; set; }
    public virtual TIPUS_INCIDENCIES TIPUS_INCIDENCIES { get; set; }
}
