//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspaiActiu
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTALACIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTALACIO()
        {
            this.HORARIS_INSTALACIO = new HashSet<HORARIS_INSTALACIO>();
            this.LLOC_DEPORTIVO = new HashSet<LLOC_DEPORTIVO>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string adreca { get; set; }
        public bool es_propi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_INSTALACIO> HORARIS_INSTALACIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLOC_DEPORTIVO> LLOC_DEPORTIVO { get; set; }
    }
}
